### ISSUE TITLE
Compiling errors

### ISSUE THREAD

**Issue by muratayoshio** [Smorodov/Multitarget-tracker#285]
Hello there trying to compile on Ubuntu 18.04

cmake . .. -DUSE_OCV_BGFG=ON -DUSE_OCV_KCF=OFF -DUSE_OCV_UKF=OFF -DBUILD_YOLO_LIB=ON -DBUILD_YOLO_TENSORRT=OFF -DBUILD_ASYNC_DETECTOR=ON -DBUILD_CARS_COUNTING=ON

These two errors appear he I compile with the option 

[ 31%] Building NVCC (Device) object src/Detector/darknet/CMakeFiles/yolo_lib.dir/src/yolo_lib_generated_network_kernels.cu.o
src/Detector/darknet/CMakeFiles/yolo_lib.dir/build.make:133: recipe for target 'src/Detector/darknet/CMakeFiles/yolo_lib.dir/src/yolo_$
CMakeFiles/Makefile2:257: recipe for target 'src/Detector/darknet/CMakeFiles/yolo_lib.dir/all' failed
Makefile:83: recipe for target 'all' failed

And this one:

In file included from /usr/include/host_config.h:50:0,
                 from /usr/include/cuda_runtime.h:78,
                 from <command-line>:0:
/usr/include/crt/host_config.h:121:2: error: #error -- unsupported GNU version! gcc versions later than 6 are not supported!
 #error -- unsupported GNU version! gcc versions later than 6 are not supported!
  ^~~~~
CMake Error at yolo_lib_generated_network_kernels.cu.o.cmake:215 (message):
  Error generating
  /root/Multitarget-tracker/build/src/Detector/darknet/CMakeFiles/yolo_lib.dir/src/./yolo_lib_generated_network_kernels.cu.o

make[2]: *** [src/Detector/darknet/CMakeFiles/yolo_lib.dir/src/yolo_lib_generated_network_kernels.cu.o] Error 1
make[1]: *** [src/Detector/darknet/CMakeFiles/yolo_lib.dir/all] Error 2
make: *** [all] Error 2

**Comment by Nuzhny007** [comment]
Hello!
It's known problem for building CUDA projects.
Here: https://github.com/jwyang/faster-rcnn.pytorch/issues/568
Or here: https://forums.developer.nvidia.com/t/cuda-9-gcc-7-compatibility-with-nvcc/60246/5

You can find fix for your version cuda and nvidia driver

**Comment by muratayoshio** [comment]
Tx you so very much
I'll try to update the driver's...

Best regards

**Comment by 17520299** [comment]
Hi, i'm a newbie in this field.
I have a problem when i configure CMakeLists.txt. i installed cmake, open_cv and opencv_contrib too but i don't know how to configure CMakeLists.txt.
And my PC is running with AMD GPUs, is it possible to run cuda?
Please help me!!! Thanks you.

**Comment by 17520299** [comment]
@muratayoshio excuse me, I'm a newbie in this field so I have a problem when i config CMakeLists.txt like this. 
![Screenshot from 2021-02-03 11-25-45](https://user-images.githubusercontent.com/71239193/106715197-62ae0580-662f-11eb-819a-d29969aefa3a.png)
Would you mind showing me your step to config Opencv_dir, please!!!(code).
Thanks you so much.
