### ISSUE TITLE
error: ‘CV_COMP_BHATTACHARYYA’ was not declared in this scope

### ISSUE THREAD

**Issue by amir-saniyan** [Smorodov/Multitarget-tracker#175]
The following error occurred when compiling with **OpenCV 4.1.2**:
```
MultitargetTracker/src/Tracker/track.cpp:123:85: error: ‘CV_COMP_BHATTACHARYYA’ was not declared in this scope
         res = static_cast<track_t>(cv::compareHist(reg.m_hist, m_lastRegion.m_hist, CV_COMP_BHATTACHARYYA));
                                                                                     ^~~~~~~~~~~~~~~~~~~~~
```

Please replace `CV_COMP_BHATTACHARYYA` with `cv::HISTCMP_BHATTACHARYYA` to compile with **OpenCV 4.1.2**.

**Comment by Nuzhny007** [comment]
Thank you!
https://github.com/Smorodov/Multitarget-tracker/pull/176
